name: Production workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: |
            sed -i 's/GITTALKCLIENTID/${{ secrets.GITTALKCLIENTID }}/g' themes/hexo-theme-matery/_config.yml
            sed -i 's/GITALKCLIENTSECRET/${{ secrets.GITALKCLIENTSECRET }}/g' themes/hexo-theme-matery/_config.yml
            npm install hexo-cli -g
            npm install
            hexo g

      - name: Deploy to netlify
        uses: teamssix/netlify-actions/cli@master
        env:
          NETLIFY_SITE_ID: ${{ secrets.PROD_NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        with:
          args: deploy --dir=public --prod